# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaires', '0002_auto_20160423_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='question',
            old_name='version',
            new_name='current_version',
        ),
        migrations.RemoveField(
            model_name='question',
            name='description',
        ),
        migrations.AddField(
            model_name='questiontext',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionnaires.Question'),
        ),
    ]
