# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 10:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaires', '0003_auto_20160424_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontext',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.CharField(default=datetime.datetime(2016, 4, 24, 10, 59, 52, 113039, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='QuestionText',
        ),
    ]
