# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaires', '0004_auto_20160424_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='current_version',
        ),
    ]
