# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaires', '0005_remove_question_current_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='min',
            field=models.IntegerField(default=0),
        ),
    ]
