# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaires', '0007_auto_20160426_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='old_questions',
            name='version',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
